# Generated by Django 5.1.6 on 2025-06-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cqid', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('party_qid', models.CharField(blank=True, max_length=20, null=True)),
                ('ideology_qid', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='candidates.candidate')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_qid', models.CharField(max_length=20, unique=True)),
                ('issue_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Politician',
        ),
        migrations.AddField(
            model_name='candidateissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.issue'),
        ),
        migrations.AddIndex(
            model_name='candidatesimilarity',
            index=models.Index(fields=['candidate'], name='candidates__candida_a96b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateissue',
            index=models.Index(fields=['issue'], name='candidates__issue_i_28a389_idx'),
        ),
    ]
