# Generated by Django 5.1.6 on 2025-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_candidateissue_candidatesimilarity_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ideology_qid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
