# Generated by Django 5.1.6 on 2025-06-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_ideology_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bioguide_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=20, unique=True)),
                ('congress', models.IntegerField()),
                ('bill_type', models.CharField(max_length=10)),
                ('bill_number', models.IntegerField()),
                ('title', models.TextField()),
                ('short_title', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('sponsor_bioguide_id', models.CharField(blank=True, max_length=10, null=True)),
                ('introduced_date', models.DateField(blank=True, null=True)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('last_action_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('congress_gov_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_bills', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_position', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Present', 'Present'), ('Not Voting', 'Not Voting')], max_length=10)),
                ('vote_date', models.DateField()),
                ('chamber', models.CharField(max_length=10)),
                ('roll_call', models.IntegerField()),
                ('congress', models.IntegerField()),
                ('session', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.bill')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['congress'], name='candidates__congres_d91439_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_type'], name='candidates__bill_ty_15fd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['sponsor_bioguide_id'], name='candidates__sponsor_02647f_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='candidates__status_ba3b74_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['bill'], name='candidates__bill_id_f822cf_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidate'], name='candidates__candida_4c9705_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['vote_date'], name='candidates__vote_da_c04507_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['chamber'], name='candidates__chamber_695660_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('bill', 'candidate', 'roll_call')},
        ),
    ]
