# Generated by Django 5.1.6 on 2025-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_bioguide_id_bill_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='main_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
