# Generated by Django 5.1.6 on 2025-06-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_main_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
