# Generated by Django 5.1.6 on 2025-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='chamber',
            field=models.CharField(blank=True, choices=[('senate', 'Senate'), ('house', 'House of Representatives')], max_length=20, null=True),
        ),
    ]
